# Combined Cycle Power Plant

In [61]:
# Downloads and installs Tensorflow packages.
!pip install tensorflow

## Importing Libraries

In [63]:
import warnings
warnings.filterwarnings('ignore')

In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [65]:
tf.__version__

'2.19.0'

## 1. Data Preprocessing

### Importing the dataset

In [68]:
dataset = pd.read_excel("dataset/Folds5x2_pp.xlsx")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [69]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [70]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [73]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [74]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [75]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [76]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


## 2. Feature Scaling

In [78]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [79]:
print(X_train)

[[-1.14 -0.89  0.67  0.52]
 [-0.81 -0.01  0.45  0.15]
 [ 1.77  1.85  0.24 -1.88]
 ...
 [-0.38 -1.25  0.85  0.13]
 [-0.92 -1.04  1.55  0.88]
 [ 1.7   1.06 -1.2  -2.42]]


In [80]:
print(X_test)

[[ 1.21  1.85 -0.62 -0.29]
 [-0.29 -0.4   1.39  0.77]
 [-0.65 -0.89  1.01  1.77]
 ...
 [-1.   -0.75  1.77  1.02]
 [ 1.02 -0.51 -1.65 -0.96]
 [-0.32 -1.13 -1.03  0.07]]


## 3. Building the ANN

### Initializing the ANN

In [83]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [85]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [87]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [89]:
ann.add(tf.keras.layers.Dense(units = 1))

## 4. Training the ANN

### Compiling the ANN

In [92]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN on the Training set

In [94]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 887us/step - loss: 206049.9688
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - loss: 197857.5312
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - loss: 163640.6250
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - loss: 99941.3750 
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - loss: 47128.1602
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - loss: 24872.2676
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - loss: 16241.9561
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - loss: 12102.1045
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - loss: 9204.4170
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - loss: 6365.7871
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - loss: 4320.8975
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - loss: 2937.6013
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - loss: 1922.8931
Epoch 14/100
240/240 ━━━━━━━━━━━━━━

## 5. Predicting the Test set results

In [96]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
[[430.79 431.23]
 [457.84 460.01]
 [462.21 461.14]
 ...
 [468.88 473.26]
 [441.69 438.  ]
 [461.38 463.28]]
