# Combined Cycle Power Plant

In [2]:
# Downloads and installs Tensorflow packages.
!pip install tensorflow

## Importing Libraries

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [6]:
tf.__version__

'2.18.0'

## 1. Data Preprocessing

### Importing the dataset

In [9]:
dataset = pd.read_excel("dataset/Folds5x2_pp.xlsx")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [10]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [11]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
print(X_train)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [15]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [16]:
print(y_train)

[473.93 467.87 431.97 ... 459.01 462.72 428.12]


In [17]:
print(y_test)

[431.23 460.01 461.14 ... 473.26 438.   463.28]


## 2. Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
print(X_train)

[[-1.13572795 -0.88685592  0.67357894  0.52070558]
 [-0.80630243 -0.00971567  0.45145467  0.14531044]
 [ 1.77128416  1.84743445  0.24279248 -1.88374143]
 ...
 [-0.38409993 -1.24886277  0.84522042  0.13092486]
 [-0.9232821  -1.04155299  1.54693117  0.8830852 ]
 [ 1.70136528  1.05824381 -1.20438076 -2.42285818]]


In [21]:
print(X_test)

[[ 1.20924389  1.84743445 -0.61878043 -0.28968211]
 [-0.29401214 -0.39528045  1.39211729  0.76937061]
 [-0.64629575 -0.88607065  1.00508258  1.77019599]
 ...
 [-0.99857936 -0.74629361  1.76737267  1.02146078]
 [ 1.02368993 -0.50992904 -1.64526378 -0.96443434]
 [-0.32090402 -1.13342892 -1.03442205  0.0651622 ]]


## 3. Building the ANN

### Initializing the ANN

In [24]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [26]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [28]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [30]:
ann.add(tf.keras.layers.Dense(units = 1))

## 4. Training the ANN

### Compiling the ANN

In [33]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN on the Training set

In [35]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 206293.6875
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - loss: 199546.6250
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - loss: 172365.4375
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 118791.2812  
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - loss: 62791.2656
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - loss: 30603.0273
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - loss: 16264.9199
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - loss: 10655.9297
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - loss: 8091.9453
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6368.2285
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - loss: 4870.6279
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - loss: 3619.7063
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - loss: 2759.6619
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━

## 5. Predicting the Test set results

In [37]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[431.61 431.23]
 [459.32 460.01]
 [463.7  461.14]
 ...
 [470.68 473.26]
 [442.12 438.  ]
 [462.3  463.28]]
