# Artificial Neural Network

## Importing the libraries.

In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf

### The following line displays the version of TensorFlow library.

In [5]:
print(tf.__version__)

2.18.0


## Part 1 - Data Preprocessing

### Importing the dataset.

In [8]:
dataset = pd.read_csv("dataset/winequality-red.csv", delimiter = ';')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
y = y.reshape(-1, 1)
print(y)

[[5]
 [5]
 [5]
 ...
 [6]
 [5]
 [6]]


### Encoding categorical data

In [11]:
from sklearn.preprocessing import OneHotEncoder
# Set sparse=False to get a NumPy array
encoder = OneHotEncoder(sparse_output = False)
y = encoder.fit_transform(y)

In [12]:
print(y)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 ...
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


### Splitting the dataset into the Training set and Test set.

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [19]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units = 128, activation='relu'))

### Adding the second hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units = 128, activation='relu'))

### Adding the output layer

In [25]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'sigmoid'))
# ann.add(tf.keras.layers.Dense(units = 6, activation = 'softmax'))

## Part 3 - Training the ANN

### Compiling the ANN

In [28]:
ann.compile(optimizer='adam', loss = 'categorical_crossentropy', metrics=['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4259 - loss: 1.4656
Epoch 2/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5940 - loss: 0.9887 
Epoch 3/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6193 - loss: 0.9309 
Epoch 4/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6371 - loss: 0.9258 
Epoch 5/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6417 - loss: 0.8872 
Epoch 6/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6109 - loss: 0.8999 
Epoch 7/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6315 - loss: 0.8731 
Epoch 8/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.8827 
Epoch 9/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6637 - loss: 0.8374 
Epoch 10/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6618 - loss: 0.8255 
Epoch 11/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6647 - loss: 0.8276
Epoch 12/100
40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - 

### Predicting the Test set results

In [30]:
y_pred = ann.predict(X_test)
y_pred_conv = np.zeros((y_pred.shape[0], y_pred.shape[1]), dtype = float)
y_pred_conv[np.arange(len(y_pred)), y_pred.argmax(1)] = 1

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


### Testing Accuracy

In [32]:
from sklearn.metrics import accuracy_score
test_accuracy = round(accuracy_score(y_test, y_pred_conv), 2)
print(test_accuracy)

0.64
